.gitignore
README.md
lua/jupynium/server.lua
requirements.txt
setup.cfg
src/jupynium/cmds/jupynium.py
src/jupynium/definitions.py

use persist queue for cross platform (native Windows support)

---

README.md
requirements.txt
setup.cfg
src/jupynium/cmds/ipynb2jupy.py
src/jupynium/events_control.py
src/jupynium/ipynb.py
src/jupynium/lua/commands.lua
src/jupynium/lua/helpers.lua

This enables loading directly from opened ipynb file from the browser to nvim and start syncing.  
Adds 2 commands
```
:JupyniumLoadFromIpynbTab tab_index
:JupyniumLoadFromIpynbTabAndStartSync tab_index
```
Also this fixes system python startup issue with `LegacyVersion` from packaging.

Load from ipynb and start sync

---

README.md
lua/jupynium/cells.lua
src/jupynium/buffer.py

I get that many people have been using the Jupytext format. This update supports Jupytext format partially (but not fully), by adding
- `# %% [md]`
- `# %% [markdown]`
as markdown cell separators.

Partial jupytext support

---

README.md
lua/jupynium/textobj.lua

Use `;` and `,` to repeat moving cells. Need [nvim-treesitter-textobjects](nvim-treesitter-textobjects) and you need to follow their instructions for key mappings.

Textobject move repeatable

---

README.md
lua/jupynium/options.lua
lua/jupynium/server.lua
pyproject.toml
requirements.txt
src/jupynium/cmds/jupynium.py
src/jupynium/lua/helpers.lua
src/jupynium/selenium_helpers.py

Run jupyter notebook when not running

---

README.md
lua/jupynium/options.lua
lua/jupynium/server.lua
src/jupynium/buffer.py
src/jupynium/cmds/jupynium.py
tests/test_buffer.py

When using profiles, addons can interfere with autostarting notebook, so it is disabled by default and users should configure it on their own.

Commented magic command becomes uncommented on notebook (#28) and profiles ini is nil by default

---

README.md
lua/jupynium/options.lua
lua/jupynium/server.lua
lua/jupynium/utils.lua
src/jupynium/cmds/jupynium.py
src/jupynium/events_control.py
src/jupynium/lua/autocmd_vimleave.lua

Fixes #32 
Additionally:
1. Able to pass multiple arguments for the commands during setup. Example:  
```lua
require("jupynium").setup({
python_host = { "conda", "run", "--no-capture-output", "-n", "base", "python" },
jupyter_command = { "conda", "run", "--no-capture-output", "-n", "base", "jupyter" },
})
```

fix windows #32

---

README.md
lua/jupynium/options.lua
lua/jupynium/server.lua
src/jupynium/cmds/jupynium.py
src/jupynium/events_control.py
src/jupynium/lua/helpers.lua
src/jupynium/nvim.py

Fixes issue #34 
1. Now, by default the tab won't close (nor stop sync) when you `:q` or `:wq`. It will still run until `BufUnload`, which means you need to delete the buffer.
Tip: Use plugins like bufferline to see which buffer is loaded or not.
2. Add an option `auto_close_tab` to configure if you want the tab to close on stop sync. Default is `true`.

feat: option not to auto close tab and change BufWinLeave to BufUnload

---

README.md
src/jupynium/events_control.py
src/jupynium/lua/helpers.lua

When running `:JupyniumStartSync` it used to default to the python3 kernel. Now, it will try to select smartly.
1. Respect language. Check filetype of the buffer and choose the kernel with the same language.
2. Respect conda env path. Check `CONDA_PREFIX` environment variable to see if it matches the kernel's spec.

feat: smart select kernel when :JupyniumStartSync

---

README.md

add geckodriver as an additional requirement. (could get it to run, tried all the methods to sync my browser with nvim turns out i didnt have geckodriver installed)

add geckodriver to requirements

---

README.md
src/jupynium/events_control.py
src/jupynium/lua/commands.lua
src/jupynium/lua/helpers.lua

`Jupynium_execute_javascript(bufnr, code)`
This can be used for #44. See README for how to get notebook kernel info.
`:JupyniumKernelInterrupt` #45 
- `:JupyniumRestartKernel` -> `:JupyniumKernelRestart`
- `:JupyniumSelectKernel` -> `:JupyniumKernelSelect`
They are new commands so I don't think many people configured it already, and also I thought it's good to start grouping types of commands

feat(API): Jupynium_execute_javascript, :JupyniumKernelInterrupt

---

src/jupynium/lua/helpers.lua

Breaking changes in #46 will be not breaking, but it will show warning.

instead of breaking, warn and deprecate

---

README.md

Addresses some of the issues discussed in #44

Updated the README to simplify steps for new users

---

src/jupynium/buffer.py
tests/test_buffer.py

Now possible to comment the markdown cell if using Jupytext format.
Addresses #52 
Example:
```python
```

feat: jupytext markdown cell content with comments

---

README.md
lua/jupynium/init.lua
lua/jupynium/server.lua
lua/jupynium/textobj.lua
src/jupynium/buffer.py
src/jupynium/cmds/jupynium.py
src/jupynium/events_control.py
src/jupynium/js/kernel_inspect.js
src/jupynium/lua/commands.lua
src/jupynium/lua/helpers.lua

- `:JupyniumKernelHover` (default binding `<space>K`): Inspect a variable from the jupyter kernel
- Shout out to https://github.com/lkhphuc/jupyter-kernel.nvim for providing the code base
- `:JupyniumStartAndAttachToServerInTerminal`: Useful for debugging
- JupyniumKernelSelect crash when escape
- Some default keybindings have changed. The default bindings are provided mainly for new users, and they may change to more sensible ones in the future. You should disable default bindings if you don't want this change!

feat: kernel hover

---

README.md
lua/jupynium/highlighter.lua
lua/jupynium/init.lua
lua/jupynium/options.lua

Added highlight groups so they can be configured outside of the jupynium `setup()`.  
Using the setup method is now deprecated.
You can link like this. The following is the default when the colour scheme is unknown:
```lua
vim.cmd [[
hi! link JupyniumCodeCellSeparator Folded
hi! link JupyniumMarkdownCellSeparator Pmenu
hi! link JupyniumMarkdownCellContent CursorLine
hi! link JupyniumMagicCommand Keyword
]]
```
Default settings for tokyonight colourscheme have been added. 
(`hi! link JupyniumMarkdownCellContent Pmenu`)

feat: highlight groups for Jupynium instead of linking

---

src/jupynium/cmds/jupynium.py

This fixes #59 by recording the initial number of tabs opened and waiting until the number of tabs equals the initial number or the initial number + 1. This is more general behaviour which checked only for equality with 1, which meant that if a profile opened tab by default, or if an extension did so, there would be a timeout error. 
I tested on the following case:
- A "blank" profile that has a single tab and keeps a single tab (default expected behaviour)
- A profile with an extension that opens a second tab as newtab (so initial number is 2)
- A profile with a pinned tab that opens automatically (so that initial number is 2, or 3 if an extension opens a new tab)
EDIT: Added cases I tested.

Handle more than one "window" (tab) when starting browser

---

README.md
after/queries/python/highlights.scm
after/queries/python/injections.scm
src/jupynium/buffer.py
src/jupynium/cmds/ipynb2jupytext.py
src/jupynium/events_control.py
src/jupynium/ipynb.py
src/jupynium/jupyter_notebook_selenium.py
tests/test_buffer.py

This PR adds support for Jupytext-style markdown cell with multi-line python string.
```python
"""
markdown content
"""
```
- Previously, we processed the cell content as we are getting updates from neovim buffer change events.
- This PR will evaluate and manipulate the content afterwards (i.e. just before it will be sent to Jupyter Notebook)
This might have a minor performance issue, but it will be more stable to do this anyway.
This may close #64 and #44.
Additionally, this fixes #65 (creating "markdown (jupytext)" cell but it's supposed to be "markdown" cell in Notebook.)

feat: post evaluate cell text (jupytext percent format with python multi-line string)

---

src/jupynium/events_control.py
src/jupynium/lua/helpers.lua

This closes #66. It works as follows:
1. Add `virtual_env_path` variable in lua and pass it to the RPC request alongside `conda_env_path`
2. If `conda_env_path` is not None, this environment is used and `virtual_env_path` is ignored
3. If `conda_env_path` is not None, the default check based on `conda_env_name` is done first.
4. If no match based on name, a cross-match is done between the executable in kernel spec and a matching executable in the environment base directory
5. If `conda_env_path` is None, step 4 is executed for `virtual_env_path`

Check for matching executable in environment path when no `conda_env_name` metadata (enables `venv` default kernels)

---

src/jupynium/cmds/ipynb2jupytext.py
src/jupynium/ipynb.py

As an avid user of Colab and Kaggle, I often come across tutorial notebooks that are filled with HTML, pictures, and Markdown content. While these elements can be helpful for learning, they can also be distracting and unnecessary when I want to run the code on my own server. Additionally, I still read the notebooks on the Colab or Kaggle pages even after I've converted them to Jupytext format.
To address this issue, I propose adding an option to ipynb2jupytext that converts only the code cells to .py format. This would make it easier to work with the code on my own machine without having to sift through the extraneous content.

Add option to ipynb2jupytext to convert only code cells

---

src/jupynium/lua/helpers.lua

Apply patch from https://github.com/lkhphuc/jupyter-kernel.nvim/commit/074fe5ddde1872b377e22b29057d523f5a227666

feat(hover): better highlighting

---

README.md
lua/jupynium/options.lua
src/jupynium/lua/helpers.lua

Allow users to configure floating win for `:JupyniumKernelHover` by passing `win_options` key in setup
```lua
require("jupynium").setup({
win_options = {
border = "rounded",
},
})
```

add option to allow user to configure floating window

---

lua/jupynium/init.lua
lua/jupynium/textobj.lua

Addresses #72 
Alternatively, we can skip the checks on setup and just expose the `set_default_keymaps` functions and leave it to the user to call them if they are lazy loading the plugin. Something like
```lua
return {
"kiyoon/jupynium.nvim",
build = "pip3 install --user .",
event = "BufWinEnter *.ju.py",
config = function()
local jupynium = require("jupynium")
jupynium.setup({})
jupynium.set_default_keymaps()
require("jupynium.textobjects").set_default_keymaps()
end
}
```

set up keymaps when plugin is lazy loaded

---

README.md
src/jupynium/events_control.py
src/jupynium/lua/commands.lua
src/jupynium/lua/helpers.lua

I managed to implement an MVP for my feature request on https://github.com/kiyoon/jupynium.nvim/issues/76. The implementation follows your suggested approach:
1. start sync
1. Request the connection info by executing javascript `Jupyter.notebook.kernel.id`
2. Open a terminal and connect to it by running `jupyter console --existing`.
This implementation supports connecting to a remote kernel by explicitly passing a hostname parameter and a naive approach(`ssh host -t`), and this require https://github.com/akinsho/toggleterm.nvim as a dependency
You can view the workflow here: 
https://user-images.githubusercontent.com/41792945/231675700-e4987167-9f4d-4225-9a62-e2c9ec690d9e.mp4
In my opinion, to improve this functionality, we may need to:
As a beginner in JavaScript and Neovim plugin …

feat: Connect to synchronized kernel

---

src/jupynium/cmds/jupynium.py
src/jupynium/lua/helpers.lua

fixes #80: replace deprecated `service_log_path` with `Service()` class

fix: deprecated selenium 4.10 options

---

lua/jupynium/cells.lua
src/jupynium/buffer.py

Jupytext suggest writing cell magic in such format:
```
```
so  this is a rough implementation, but it seems to be working well.

support jupytext py:percent flavor cell magic

---

README.md
lua/jupynium/options.lua
src/jupynium/cmds/jupynium.py
src/jupynium/selenium_helpers.py

Now, users who install notebook will install Notebook 7 by default. Thus, this PR changes the default options so that it will work with URL `http://localhost:8888/nbclassic`.
Make sure to install `pip install --upgrade notebook nbclassic`

fix!: Notebook 7 uses localhost:8888/nbclassic

---

lua/jupynium/cells.lua

Note that a proper fix is doing partial update just like it is done in the python package, using `vim.api.nvim_buf_attach` with `on_lines`. See `src/jupynium/buffer.py` for its logic.
Due to the complexity, this is a temporary fix that will cache the result and avoid re-calculation of line types.
Fixes #89

perf: cache `cells.line_types_entire_buf` to avoid repeated calls

---

README.md
lua/jupynium/cells.lua
lua/jupynium/init.lua

I think it would be great to make cells to be foldable :eyes: 
fold:
Here is the setup for ufo(I note you also use this) https://github.com/fecet/nvim/blob/main/lua/modules/configs/editor/ufo.lua:
```lua
return function()
local ufo = require("ufo")
vim.o.fillchars = [[eob: ,fold: ,foldopen:,foldsep: ,foldclose:]]
vim.o.foldcolumn = "1" -- '0' is not bad
vim.o.foldlevel = 99 -- Using ufo provider need a large value, feel free to decrease the value
vim.o.foldlevelstart = 99
vim.o.foldenable = true
local function get_cell_folds(bufnr)
local function handleFallbackException(err, providerName)
if type(err) == "string" and err:match("UfoFallbackException") then
return ufo.getFolds(bufnr, providerName)
else
return require("promise").reject(err)
end
end
return ufo.getFolds(bufnr, "lsp") …
```

feat: add function for custom folds

---

src/jupynium/cmds/jupynium.py

Without stderr, kernels fail to start and JupyniumStartSync times out.
fixes #97

fix: attach stderr to jupyter process

---

src/jupynium/lua/helpers.lua

In addition, detach on_lines event handler when not needed any more.
Fixes #92

Avoid attaching on_lines handler multiple times

---

after/queries/python/highlights.scm
after/queries/python/injections.scm
lua/jupynium/cells.lua
lua/jupynium/highlighter.lua
lua/jupynium/init.lua
lua/jupynium/server.lua
lua/jupynium/utils.lua

- Remove deprecated old markdown syntax (`"""%% .. %%"""`)
- `utils.string_begins_with()` -> `vim.startswith()`

refactor!: remove deprecated syntax

---

src/jupynium/lua/commands.lua
src/jupynium/lua/helpers.lua

Removed following commands:
- `:JupyniumRestartKernel`
- `:JupyniumSelectKernel`
- `Jupynium_restart_kernel`
- `Jupynium_select_kernel`

refactor!: remove deprecated commands

---

lua/jupynium/cells.lua
src/jupynium/events_control.py

Fixes #123 and more.
1. Fix error when opening an empty .ju.py buffer.
2. Fix error when there is no default system python3 kernel. It happened to me when I installed `conda install nb_conda_kernels`

fix: error in empty ipynb and default kernel not existing

---

lua/jupynium/cells.lua
src/jupynium/buffer.py
tests/test_buffer.py

This pull request enhances the parser to correctly recognize lines that start with `# %%`, even when followed by additional comments ~~or markdown annotations~~. This improvement is achieved by using regular expressions.
- **Enhancement**: Refactored the parser to use regex for identifying cells that start with `# %%` and may include additional comments or markdown annotations.
- Added regex-based identification of cells to the parser.
- Imported the `re` module to facilitate regex matching.
The existing parser did not handle lines starting with `# %%` when followed by additional comments or markdown annotations. By using regular expressions, the parser can now accurately identify such lines, improving its robustness and flexibility.
- Verified that the parser correctly identifies cells …

Enhance Parser to Support # %% with Additional Comments
